### ISSUE TITLE
Feature Request - Date Added

### ISSUE THREAD

**Issue by McGreggor** [SchapplM/xbmc-addon-service-watchedlist#26]
Please add in 'date added' field to the database for each unique film/tv show.  This should record the earliest date found for each ID, and then overwrite any newer dates found for the same unique film/show.  When ever paths are moved, this add-on updates the watched status nicely, but kodi still marks it as 'newly added' based on this date, so would be great to add this in too.

**Comment by SchapplM** [comment]
If you sort your media after [dateAdded](http://kodi.wiki/view/Databases) in Kodi, after moving the folders, all folders have the time of the file moving as dateAdded which is unwanted?
From my experience, dataAdded often does not contain the date I first copied the file into Kodi, but the date of the file itself (from filesystem) .

**Comment by McGreggor** [comment]
I think you're right, 'files' table seems to use the filesystem date, which I've preserved by using robocopy to move my folders around, but I was looking at the 'path' table which uses the date the folder was added, and this _does_ get amended to the date/time it was re-added.   Strangely, all the movies in the path table show a NULL dateAdded.  It was this column in the path table I was referring to, but not sure what this is used for, all the TV/Movies views that are sorted on date/added display as you describe.

**Comment by SchapplM** [comment]
In my database only 70 of 2500 `path` entries have dataAdded set different than NULL.
It could be, that only a manual rescraping of a movie or tv season leads to an entry here.
So if the dateAdded mainly comes from the `files` table, I think this feature would cause too much effort for the WatchedList addon (would need a database refactoring and database migration mechanism for compatibility).

**Comment by McGreggor** [comment]
sure, thanks for looking in to this.
