### ISSUE TITLE
Doesn't work with SMB paths in windows

### ISSUE THREAD

**Issue by eblieb** [SchapplM/xbmc-addon-service-watchedlist#27]
I have Kodi installed from the windows store on Windows 10.. The SMB path for the db file doesnt work on windows... I tested SMB paths on android and it works fine... says Can't access file at \\SMBpath\path\watchedlist.db (I changed the path names but I know they are correct on my settings).

**Comment by SchapplM** [comment]
Can you provide the related lines in kodi.log with verbose log level?
Since this already worked in various Windows systems I think it might be something specific for your computer and not a general problem.
Also please shift this to the WatchedList thread in the Kodi forum.

**Comment by SchapplM** [comment]
I closed this prematurely, as the problem was reproduced by other users.
Fix in https://github.com/xbmc/repo-scripts/pull/769 and discussed [here](https://forum.kodi.tv/showthread.php?tid=164652&pid=2699987#pid2699987).
