### ISSUE TITLE
Dropbox API v1 retired. Use API v2

### ISSUE THREAD

**Issue by SchapplM** [SchapplM/xbmc-addon-service-watchedlist#30]
The Dropbox API version 1 used here is not[ supported by Dropbox any more](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/). [It was deactivated end of september 2017](https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/).
Error message in WatchedList:

> NOTICE: service.watchedlist: Dropbox database download failed. [400] u'v1_retired'.

[Refactor the code](https://www.dropbox.com/developers/reference/migration-guide) to use Dropbox API v2:

**Comment by SchapplM** [comment]
@micahg: I just found out that you [already started working on the issue](https://github.com/micahg/xbmc-addon-service-watchedlist/tree/dropbox_v2).
I also did a [similar refactoring](https://github.com/SchapplM/xbmc-addon-service-watchedlist/tree/dropbox_api_v2), but you also seem to have run [into the error ](https://github.com/dropbox/dropbox-sdk-python/issues/106) I had with
`dbx.files_download_to_file(self.dropbox_path, remote_file)`: 
`ValueError('Timeout value connect was Timeout(connect=30, read=30, total=None))`.
So I will wait what you find out.

**Comment by micahg** [comment]
Hi,

Yeah, it has to do with the script.modules.requests version. That needs a version bump (requested at https://github.com/beenje/script.module.requests/issues/16).

**Comment by OptimusGREEN** [comment]
I didn't implement any fix for dbx.files_download_to_file(self.dropbox_path, remote_file) but haven't had any issues.  Unless my make stone friendly fix had anything to do with it. It was an issue cause by date time formatting i believe.
