### ISSUE TITLE
Dropbox error in Windows 10 with Kodi 17.6

### ISSUE THREAD

**Issue by mriscoc** [SchapplM/xbmc-addon-service-watchedlist#32]
When Addon is started and Dropbox Synchronization is active: 

**NOTICE: service.watchedlist: Notification. Dropbox Error: Error importing python Dropbox API. Disable function**

Windows 10 with Kodi 17.6

**Comment by SchapplM** [comment]
can you provide a debug log (preferably via pastebin), information about your system architecture and if you installed via installer or via the Microsoft Store?
