### ISSUE TITLE
LOGSEVERE and LOGNOTICE will deprecated in kodi/python addons

### ISSUE THREAD

**Issue by phunkyfish** [SchapplM/xbmc-addon-service-watchedlist#47]
Please replace with LOGFATAL and LOGINFO. They will be removed in a couple of weeks.

PR: https://github.com/xbmc/xbmc/pull/18346
Forum Post: https://forum.kodi.tv/showthread.php?tid=353818

**Comment by SchapplM** [comment]
merged in this repo and in kodi repo-scripts

**Comment by phunkyfish** [comment]
Thanks!
