### ISSUE TITLE
Fix reference to sometimes not available IMDB number

### ISSUE THREAD

**Issue by SchapplM** [SchapplM/xbmc-addon-service-watchedlist#53]
As [reported in the forum](https://forum.kodi.tv/showthread.php?tid=164652&pid=3072036#pid3072036), the switch to TMDB as default scraper lead to many media in the library not having an IMDB id. The WL addon only uses the IMDB id for historic reasons (was the only ID when development started).
One possible solution would be to restructure the WL database to incorporate different scraper IDs (e.g. also TMDB).
A faster workaround would be to use the IMDB mechanism of the addon "[Light IMDb Ratings Update](https://forum.kodi.tv/showthread.php?tid=316342)".

**Comment by Nionor** [comment]
Yup that addon only looks it up through the tmdb api, so you can ask for external id and get imdb id (and others) back.
e.g
`{"id":451048,"imdb_id":"tt0870154","facebook_id":"JungleCruise","instagram_id":"disneysjunglecruise","twitter_id":"JungleCruise"}`

**Comment by Nionor** [comment]
I had a quick look around today and saw there is a uniqueid in the kodi-db and if you query for it you get both imdb and tmdb values, from what I can see even if you haven't scraped with the imdb scraper.
So I tried to just add the uniqueid to the rpc call and change the **item['imdbnumber']** to **item['uniqueid']['imdb']** and it read in all my watched movies fine after that.

The WL db came from a LibreELEC 9.2.8 and was imported to Kodi 19.2 and before I got the "has no imdb-number or themoviedb-number in database" error for all movies.

**Comment by SchapplM** [comment]
Thanks for looking into this. Can you provide a pull request?
Then I can test directly and merge to the official addon repo.

**Comment by Nionor** [comment]
Done, but as I wrote in the pull I haven't tested this much at all.

**Comment by SchapplM** [comment]
[Done](https://github.com/SchapplM/xbmc-addon-service-watchedlist/pull/54#issuecomment-981036946).
