### ISSUE TITLE
WatchedList Errors

### ISSUE THREAD

**Issue by HPMSGEN8** [SchapplM/xbmc-addon-service-watchedlist#56]
Good Day,

I had an crash and i needed to start over. So now the WatchedList Add-on will not connect to the MariaDB5 or 10 on my Synology.

Also where is all the DB Files located so i can try and recover if it will let me, 

I am getting Open DB Error. Any help on how to fix this please.

Thanks

**Comment by SchapplM** [comment]
Please post your questions in the [forum](https://forum.kodi.tv/showthread.php?tid=164652), as you are not reporting a concrete error case, but rather seem to search for general support.
