### ISSUE TITLE
Contributing help

### ISSUE THREAD

**Issue by MarcoSmeulders** [SchapplM/xbmc-addon-service-watchedlist#58]
I want to make a small contribution to this project by translating the interface to Dutch. As a front-end developer I've never done anything with Python, but I'll figure it out. But does anyone have any tips on how to test this Kodi addon locally?

**Comment by SchapplM** [comment]
Thanks for your interest in contributing.

First install the addon via Kodi, so all dependencies will be installed.
Fork the addon repository on GitHub.
Then go to the addon directory and clone the (forked) Git repository there by using the same folder names. By this, the addon folder now is under version control and you can upload your changes on GitHub.
Then, create a language file, similar to the existing ones (in ressources/language) and try your translation becomes visible in Kodi.

If you just want to translate the interface, you don't need Python at all (and probably won't learn it by doing this).
This will more likely let you learn the process of programming Kodi addons.

**Comment by SchapplM** [comment]
btw. this is not really an issue in the sense of GitHub. Post questions on the [Kodi forum](https://forum.kodi.tv/showthread.php?tid=164652).

**Comment by MarcoSmeulders** [comment]
Thanks for the clear instructions and help!
