### ISSUE TITLE
Scanning all day long, why?

### ISSUE THREAD

**Issue by eusi** [SchapplM/xbmc-addon-service-watchedlist#60]
Hi,
I think the addon is scanning all day long on my Kodi (19). My kodi.log: https://pastebin.com/nTXvZDpn

It looks like this:
```
2023-11-25 10:59:08.936 T:10185    INFO <general>: service.watchedlist: get_watched_xbmc: Movie X (2021) has no imdb-number in database. movieid=6900. IDs are ['tmdb']. Try rescraping
2023-11-25 10:59:14.285 T:10185    INFO <general>: service.watchedlist: get_watched_xbmc: Episode id 16318 (show 473, S01E06) has no field uniqueid in database. Try rescraping.
... (a lot more episodes with same issue)
2023-11-25 11:00:46.767 T:10185    INFO <general>: service.watchedlist: get_watched_xbmc: Movie X (2021) has no imdb-number in database. movieid=6900. IDs are ['tmdb']. Try rescraping
```

This runs the entire day over and over again (see time stamp).

Due to my settings this should only be done once every 12h. Or have I configured something wrong?

```<settings version="2">
    <setting id="w_movies">true</setting>
    <setting id="w_episodes">true</setting>
    <setting id="autostart">true</setting>
    <setting id="delay">0</setting>
    <setting id="starttype">2</setting>
    <setting id="interval">12</setting>
    <setting id="watch_user">true</setting>
    <setting id="progressdialog">false</setting>
    <setting id="verbosity">0</setting>
    <setting id="db_format">1</setting>
    <setting id="extdb" default="true">false</setting>
    <setting id="dbpath" default="true" />
    <setting id="dbfilename" default="true">watchedlist.db</setting>
    <setting id="dbbackupcount">-1</setting>
    <setting id="dropbox_enabled" default="true">false</setting>
    <setting id="dropbox_apikey" default="true" />
    <setting id="mysql_server">192.168.178.10</setting>
    <setting id="mysql_port">3306</setting>
    <setting id="mysql_db">KodiWatchedList</setting>
    <setting id="mysql_user">...</setting>
    <setting id="mysql_pass">...</setting>
</settings>
```

Thanks for your help!
eusi

**Comment by SchapplM** [comment]
If you post a complete log it could be easier to determine why it scans "all day long". From the excerpt I can only tell that you have media in your database without unique or matching IDs for the watchedlist addon.

You have activated the option "watch user". That means every time you browse the menu, the addon tries to see if you have marked something as unwatched by comparing the state of all media to a previous version. Unfortunately I did not see another way to implement this feature. With that option on you should solve the missing unique IDs or reduce log verbosity to not have that spam the log.

So short answer: Try disabling "watch_user". Also please post reports like this in the forum, as other users could help you there as well. I will close this issue as I think this is related to your database and the watch-user option and is not an issue in the program.
